export const CREATE_EVENT_DISCOUNT_REQUEST = "CREATE_EVENT_DISCOUNT_REQUEST";
export const CREATE_EVENT_DISCOUNT_SUCCESS = "CREATE_EVENT_DISCOUNT_SUCCESS";
export const CREATE_EVENT_DISCOUNT_FAIL = "CREATE_EVENT_DISCOUNT_FAIL";

export const CREATE_ALUMNI_DISCOUNT_REQUEST = "CREATE_ALUMNI_DISCOUNT_REQUEST";
export const CREATE_ALUMNI_DISCOUNT_SUCCESS = "CREATE_ALUMNI_DISCOUNT_SUCCESS";
export const CREATE_ALUMNI_DISCOUNT_FAIL = "CREATE_ALUMNI_DISCOUNT_FAIL";

export const GET_ALL_DISCOUNTS_REQUEST = "GET_ALL_DISCOUNTS_REQUEST";
export const GET_ALL_DISCOUNTS_SUCCESS = "GET_ALL_DISCOUNTS_SUCCESS";
export const GET_ALL_DISCOUNTS_FAIL = "GET_ALL_DISCOUNTS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
