version: '3.8'

services:
  backend:
    build:
      context: ./moji-web-main
      dockerfile: Dockerfile
    image: hiumonday/moji-backend:latest
    container_name: moji-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./moji-web-main:/be_moji
      - /be_moji/node_modules
    restart: unless-stopped

  frontend:
    platform: linux/amd64
    build:
      context: ./moji-web-frontend-main
      dockerfile: Dockerfile
    image: hiumonday/moji-frontend:latest
    container_name: moji-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped